name: Migrate

on:
  push:
    # branches: [main]
    # paths: ["src/services/database/migrations/*"]
  pull_request:
    branches: ["*"]
  merge_group:

jobs:
  migrate:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.12]

    steps:
      - name: Print event
        run: echo ${{ github.event_name }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v4
        with:
          version: ${{ matrix.pnpm-version }}

      - name: Create .env file
        run: |
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env

      - name: Install dependencies
        run: SKIP_VALIDATION=true pnpm i --frozen-lockfile

      - name: Push schema changes
        run: pnpm db:migrate
